name: build
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  build:
    name: Build
    defaults:
      run:
        working-directory: ./node-product-api
    runs-on: ubuntu-20.04    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        trivy-config: trivy.yaml